window.uiText = {
    zh:{
        volume: '音量',
        pitch: '音调',
        allMusic: '所有音乐',
        search: '搜索',
        searchContent: '搜索内容',
        playQueue: '播放队列',
        setting: '设置',
        settingTab: '设置',
        aboutTab: '关于',
        settingClassicKaraoke: "经典卡拉OK显示模式 (播放下一首歌时生效)",
        settingAudioSpectrum: "音频频谱显示 (立即生效)",
        settingCountdownTimeDisplayTime: '倒计时开始显示的时间 当前选择',
        settingLyricFontSize: '歌词字体大小',
        settingCountdownTimeDisplayAccuracy: '倒计时时间精度',
        settingLanguage: '语言',
        aboutProjectLink: '项目链接',
        aboutNote: '注意:在本项目Demo中,如果演示歌曲侵权,请与我联系,我会将其删除! :)',
    },
    en: {
        volume: 'volume',
        pitch: 'pitch',
        allMusic: 'all Songs',
        search: 'search',
        searchContent: 'search Content',
        playQueue: 'play Queue',
        setting: 'setting Options',
        settingTab: 'setting',
        aboutTab: 'about',
        settingClassicKaraoke: "Classic karaoke display mode (active when playing the next song)",
        settingAudioSpectrum: "Audio spectrum display (immediately)",
        settingCountdownTimeDisplayTime: 'The time at which the countdown starts to be displayed The current selection',
        settingLyricFontSize: 'Lyrics font size',
        settingCountdownTimeDisplayAccuracy: 'Countdown time display accuracy',
        settingLanguage: 'language',
        aboutProjectLink: 'project link',
        aboutNote: 'Note: In this project Demo, if the demo song is infringing, please contact me, I will delete it! :)',
    }
}